spin_manifest_version = 2

[application]
name = "example"
version = "0.1.0"
description = "A simple HTTP handler"

[[trigger.http]]
route = "/..."
component = "example"

[component.example]
environment = { CLIENT_ID = "<YOUR GITHUB CLIENT ID>", CLIENT_SECRET = "<YOUR GITHUB CLIENT SECRET>" }
source = "service.wasm"
allowed_http_hosts = ["github.com", "api.github.com"]
[component.example.build]
command = "./build.sh"
