name = "example"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = [
    "wasmcloud:httpserver",
    "wasmcloud:httpclient"
]

wasm_target = "wasm32-wasi-preview2"
wit_world = "demo:example/example"
