spin_manifest_version = 2

[application]
name = "http-handler"
version = "0.1.0"
authors = ["Brian H <brian.hardock@fermyon.com>"]
description = "A simple HTTP handler"

[[trigger.http]]
route = "/..."
component = "http-handler"

[component.http-handler]
source = "../service.wasm"
# source = "target/wasm32-wasi/release/http_handler.wasm"
allowed_http_hosts = []
[component.http-handler.build]
command = "cargo component build --release"
